### ISSUE TITLE
Blog: URLs need fixing

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#104]
Staging URL:

blog2.threefold.io

Production:

blog.threefold.io

both show 
![image](https://user-images.githubusercontent.com/64129/82322968-a5fc1180-99d7-11ea-9c06-60efae7dc5e0.png)

**Comment by xmonader** [comment]
resolved https://github.com/threebotserver/publishingtools/blob/development/deployment/Caddyfile
