### ISSUE TITLE
Blog: Initial screen pops up on (re)loading. 

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#105]
Very strange UX having that image flash and then jump to the blog.
Maybe solve with a spinner?

![Screenshot 2020-05-16 at 11 54 12](https://user-images.githubusercontent.com/29431263/82116721-1868b980-976c-11ea-9ede-28193df6361c.png)

**Comment by xmonader** [comment]
fixed in cacdb60381277bfdc761e1c59daf071bf0c79ca3
