### ISSUE TITLE
Blog: Social Media Logo's Dissapeared

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#106]
On the previous version the empty rectangle would feature our social media links (logos).
These seem to be gone now, could we bring these back?
![Screenshot 2020-05-16 at 11 56 15](https://user-images.githubusercontent.com/29431263/82116759-451cd100-976c-11ea-85c9-7fd04127c5ce.png)

**Comment by xmonader** [comment]
71622d33b7e5755d9d08e8f5c1ae526fbbf9cebe

![image](https://user-images.githubusercontent.com/64129/82349245-292e5f00-99fa-11ea-9fdb-3b2800199759.png)

**Comment by samtaggart** [comment]
This still looks funky.

- There is no Facebook Logo just the word "Facebook."
- Twitter has both.
- We do not link to our LinkedIn or Telegram.

I would rather it just be logos for:

Facebook
Twitter
LinkedIn
Telegram

**Comment by abom** [comment]
@samtaggart The footer social media links are fixed to threefold (as this wikis 
The logos on the right are user defined per blog,  the user needs to specify the `faclass` for the icon, the text...etc.

**Comment by samtaggart** [comment]
I'm sorry! I don't understand. Is it something we can fix or not?
