### ISSUE TITLE
Blog: Date issues

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#107]
1. we need to know the format with is expected (YYYY/MM/DD or YYYY/DD/MM). if it is the latter we need to convert that to this format: DD/MM/YYYY
2. The blog does not sort by dates, we either need to fix that or do something with a ranking.
If we go with ranking, I suggest we go with "reverse" ranking. 1 being the oldest as this means we only need to edit 1 file when updating a new entry.

**Comment by xmonader** [comment]
it's fixed already here e9f7d5937c4fe3efa48b4447ce4853bf8207a890

**Comment by VonSub** [comment]
@xmonader Please tell us what format it wants us to use then, we could not get it to work for some reason

**Comment by xmonader** [comment]
@VonSub 

![image](https://user-images.githubusercontent.com/64129/82321804-bca16900-99d5-11ea-8ccf-6c8aaf2daa8a.png)
