### ISSUE TITLE
Blog: Empty Tags on Display

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#110]
We feature tags in the sidebar that have no posts attached for some reason. Bit strange
![Screenshot 2020-05-16 at 12 03 25](https://user-images.githubusercontent.com/29431263/82116921-6f22c300-976d-11ea-8598-875b1d4b6f9c.png)

**Comment by VonSub** [comment]
When clicking partner under this post it does load, when clicking it in the sidebar it's empty. Seems somethings up.
![Screenshot 2020-05-16 at 12 05 53](https://user-images.githubusercontent.com/29431263/82116966-af824100-976d-11ea-9407-5022384585b4.png)
![Screenshot 2020-05-16 at 12 08 26](https://user-images.githubusercontent.com/29431263/82117046-f8d29080-976d-11ea-84ec-4707d51cb021.png)
![Screenshot 2020-05-16 at 12 08 12](https://user-images.githubusercontent.com/29431263/82117050-fd974480-976d-11ea-8bd6-030f65dceca8.png)

**Comment by xmonader** [comment]
fixed in d2c6853159a16e5384b529f5a205c745551ef99e
