### ISSUE TITLE
Blog: Mobile UI Avatar Issue

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#111]
It does not load the right avatars. when you go from page 1 to page 2 the everything from the posts on page two is right expect it features the avatars from the previous page..

**Comment by VonSub** [comment]
Seems like this happens on pc as well:

Page 1: looks normal
![Screenshot 2020-05-19 at 16 56 44](https://user-images.githubusercontent.com/29431263/82342423-e072a800-99f1-11ea-8b80-3eeb966396eb.png)



Page2: takes all author images + post images from page one
![Screenshot 2020-05-19 at 16 56 49](https://user-images.githubusercontent.com/29431263/82342413-dea8e480-99f1-11ea-8fd0-73e7ddc324b4.png)

Page2: after refreshing shows the right images

![Screenshot 2020-05-19 at 16 56 52](https://user-images.githubusercontent.com/29431263/82342399-da7cc700-99f1-11ea-96da-74a832bc69e9.png)

**Comment by xmonader** [comment]
fixed in a00a22e1f94c905b5462c3d4db8a73be24770150 c829a56ad49274f973bb1a4d462d8bbf3884549a
