### ISSUE TITLE
Blog: Markdown Issue with Bullets

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#119]
<img width="723" alt="Screen Shot 2020-05-20 at 12 56 32 PM" src="https://user-images.githubusercontent.com/50134479/82438558-8c230300-9a99-11ea-891e-120132d067bf.png">

Bullets not showing up correctly even though showing up properly here:

<img width="933" alt="Screen Shot 2020-05-20 at 12 58 26 PM" src="https://user-images.githubusercontent.com/50134479/82438623-a230c380-9a99-11ea-91d4-626ce310c6d7.png">

**Comment by xmonader** [comment]
fixed in 035940105f9fe960f1d44bf535ffc23b0e91eef7
