### ISSUE TITLE
kemal does not find its way?

### ISSUE THREAD

**Issue by despiegk** [threebotserver/publishingtools#12]
![image](https://user-images.githubusercontent.com/6021844/80274890-0f8d4680-86de-11ea-9e83-305cf8feeaf1.png)

**Comment by despiegk** [comment]
no error, not nothing

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/80722468-aeaba700-8aff-11ea-90cf-9a5fe9804122.png)
