### ISSUE TITLE
Blog: Some social media icons are grey, some are colored. Can we have all colored please?

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#120]
<img width="360" alt="Screen Shot 2020-05-20 at 1 11 23 PM" src="https://user-images.githubusercontent.com/50134479/82440004-ecb33f80-9a9b-11ea-8726-0bbd6c5b9a7f.png">
<img width="490" alt="Screen Shot 2020-05-20 at 1 13 02 PM" src="https://user-images.githubusercontent.com/50134479/82440007-ed4bd600-9a9b-11ea-8d77-2671f4ad0783.png">

**Comment by xmonader** [comment]
3dc22d918f836a530391311d655b474e926a1e22

you can use colorcode attribute in metdata now https://github.com/threebotserver/publishingtools/blob/development/docs/blog.md
