### ISSUE TITLE
Blog: Images not loading

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#121]
<img width="469" alt="Screen Shot 2020-05-20 at 1 21 20 PM" src="https://user-images.githubusercontent.com/50134479/82440624-ed000a80-9a9c-11ea-8336-130b34c7fba8.png">

But loads correctly in the header.

<img width="687" alt="Screen Shot 2020-05-20 at 1 23 05 PM" src="https://user-images.githubusercontent.com/50134479/82440696-11f47d80-9a9d-11ea-975d-0c263465a963.png">

Code looks correct:

<img width="432" alt="Screen Shot 2020-05-20 at 1 22 30 PM" src="https://user-images.githubusercontent.com/50134479/82440664-030dcb00-9a9d-11ea-9f84-982fc654cd25.png">

**Comment by xmonader** [comment]
a bug indeed, the only way to reference is using /tfblo2/assets/images/ciruclar_economy.jpg to resolve correctly, that's how it's done in the post image link 

@abom probably can fix it using referrer header.

**Comment by xmonader** [comment]
Fixed in https://github.com/threebotserver/publishingtools/pull/133 and deployed. it's up to the content author to make sure they use the correct images :)

**Comment by samtaggart** [comment]
Thanks!
