### ISSUE TITLE
Blog: Add social sharing buttons

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#128]
Would like to add buttons for social sharing:

<img width="207" alt="Screen Shot 2020-05-25 at 12 17 45 PM" src="https://user-images.githubusercontent.com/50134479/82804017-cae20000-9e81-11ea-975f-300789f2c6cd.png">

Ideally somewhere in this area:

<img width="784" alt="Screen Shot 2020-05-25 at 12 18 37 PM" src="https://user-images.githubusercontent.com/50134479/82804075-e77e3800-9e81-11ea-8b8e-babebfb7b91f.png">

**Comment by xmonader** [comment]
if you change `allow_disqus` param to true in your metadata.yml, that was disabled based on your team request.

![image](https://user-images.githubusercontent.com/64129/83147100-8495d680-a0f7-11ea-83bf-b668a100ad93.png)

**Comment by samtaggart** [comment]
Does this have to be through Disqus?

I don't like the way it looks, and I don't really want comments enabled. Also can we add the buttons in a different location?

**Comment by samtaggart** [comment]
For example:

<img width="790" alt="Screen Shot 2020-06-03 at 8 54 35 PM" src="https://user-images.githubusercontent.com/50134479/83677458-7e629700-a5dc-11ea-911b-33517c27367c.png">

**Comment by samtaggart** [comment]
Wanted to check in here. @xmonader @samaradel
