### ISSUE TITLE
Can't build tfweb binary

### ISSUE THREAD

**Issue by AhmedHanafy725** [threebotserver/publishingtools#148]
![image](https://user-images.githubusercontent.com/41957921/84762077-a1248080-afca-11ea-8000-6e59cc163ff6.png)

**Comment by xmonader** [comment]
should be fixed now for crystal 0.34

**Comment by AhmedHanafy725** [comment]
It works, but docs need to be updated with libs needed before building the binary.

![image](https://user-images.githubusercontent.com/41957921/84923434-7e2bc680-b0c7-11ea-90eb-44c1bc2dc09d.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
Docs updated 
**Commit:** 082abb3376696d7daf75630ec660e9fe4c842148
