### ISSUE TITLE
Blog UI Impovement: Link Color

### ISSUE THREAD

**Issue by VonSub** [threebotserver/publishingtools#154]
The link color now is a "faded grey" wich hides hyperlinks more than makes them pop.
This would also be a good thing to make changeable in the metadata as not all blogs will us the same colors.

For now we would love: #2774BB to be the link color.
![Screenshot 2020-06-30 at 13 05 53](https://user-images.githubusercontent.com/29431263/86119490-dc4aa780-bad2-11ea-93f9-bddd5291a31b.png)

**Comment by xmonader** [comment]
moved to https://github.com/threefoldfoundation/blog_threefold/issues/29
