### ISSUE TITLE
could not load wiki from simulator 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threebotserver/publishingtools#158]
```
rm -rf ~/.cache/shards
rm -rf  ~/.cache/crystal
git clean -fxd
shards build
./bin/tfweb -c /home/rafy/sandbox/code/github/threefoldtech/simulator/config/tfweb.toml
```
![image](https://user-images.githubusercontent.com/46320202/87296246-c68fa600-c506-11ea-9653-469b661726a6.png)

**Comment by xmonader** [comment]
as said the repo path should be in the defined path because you used environment, if you want to use this path make sure environment is set to empty string
