### ISSUE TITLE
link replace tools wrong

### ISSUE THREAD

**Issue by despiegk** [threebotserver/publishingtools#16]
![image](https://user-images.githubusercontent.com/6021844/80275226-3e0c2100-86e0-11ea-8d26-030b01b8f004.png)

link dissapears

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/80279423-e4b2ea80-86fd-11ea-8d1c-fa6e7b6cbe76.png)
shouldn't be happening anymore.
