### ISSUE TITLE
wrong cloning

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#169]
with this https://github.com/crystaluniverse/publishingtools/blob/development/deployment/threefoldwebsitesandwikis.toml i find 

code_production for /code_production/github/threefoldfoundation/info_foundation# always development while it should be master

**Comment by xmonader** [comment]
should be done already @abom please link to the right commit resolving this issue and close

**Comment by abom** [comment]
Fixed in [crystaltools](https://github.com/crystaluniverse/crystaltools/commit/19febe7280e8e614d3dba83eba5718806dadd1bc
) and the [added shard.lock](https://github.com/crystaluniverse/publishingtools/commit/6976f12ce5a43281f6da6f409f4ea40b30184ccb) to reference latest version.
