### ISSUE TITLE
don't allow multiple force_updates in the same time

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#178]
![image](https://user-images.githubusercontent.com/64129/88631935-3d09d780-d0b3-11ea-92d2-ebc34c12ba12.png)

used `hey wiki2.threefold.io/force_update -n 4 -c 4`

probably we can get away with checking on index.lock in the git repo?

**Comment by abom** [comment]
Should be fixed by https://github.com/crystaluniverse/publishingtools/pull/182
