### ISSUE TITLE
review the image fixer

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#186]
should collect the images and create a dir `img` (let's double check on that behavior)

**Comment by abom** [comment]
It's working as expected by creating `img` directory and move images to it.

Also, images can be viewed normally:

![Screenshot from 2020-08-04 14-37-50](https://user-images.githubusercontent.com/511438/89294736-36a1cf80-d660-11ea-8cc9-1faa3127200e.png)
