### ISSUE TITLE
publishingtools can't detect new remote branches

### ISSUE THREAD

**Issue by sasha-astiadi** [threebotserver/publishingtools#199]
when launched, and accessing repos from ./code/github/threefoldfoundation
and try to edit wiki files from src folder,
the branches listed are only development and master.
tried to git fetch but nothing new. it doesnt detect remote branches

**Comment by xmonader** [comment]
publishingtools works with shallow clone against specific branch and that repo is contained in environment that controls your code dir name, if no environment specified your code dir will be `~/code` if specified it will be `~/code_ENVNAME`

# how to work around this
create a new section in the config 

```
[[wiki]]
name = "MY_NEW_NAME"
title = "Grid Manual"
url = "git@github.com:threefoldfoundation/info_tfgridsdk.git"
path = ""
autocommit = false
branch = "MY_OTHER_BRANCH"
branchswitch = false
srcdir = "src"
environment = "MY_ENVIRONMENT"
```


so this will create a wiki in `~/code_MY_ENNVIRONMENT/github/threefoldfoundation/info_tfgridsdk` on branch `MY_OTHER_BRANCH`
