### ISSUE TITLE
make example caddy2 config / configure dns names

### ISSUE THREAD

**Issue by despiegk** [threebotserver/publishingtools#22]
create a caddy example config to go from

- www3.threefold.io 
- wiki3.threefold.io

...

- on caddy reverse proxy to the localhost:3000/$sitename
- some rewrite rules will be required

how will it be hosted?

- 3 pub hosts in DO will serve as endpoints, accept 443
- caddy on machine kristof for now (local machine)
- portforward from 443 on pub ssh host to the local one on the caddy 443
- this should also get letsencrypt to work

configure the names in name.com
all use 3... 

we will get it to work on those

**Comment by xmonader** [comment]
on development README.md
