### ISSUE TITLE
integrate blog apis

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#39]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/blog/package.py

- [x] add new type of websites (a blog website) in the toml config 
- [x] make sure all of the supported APIs work
- [x] that we can start blogs using that sapper application
- [x] fix rendering problems

**Comment by abom** [comment]
Still having a problem where some components gets rendered anyway when entering the URL directly for any blog or post.

**Comment by abom** [comment]
#63.
