### ISSUE TITLE
simulator support [development_simulator]

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#44]
data repo [simulator_export](https://github.com/threefoldfoundation/simulator_export) 

# API endpoints
should have an API endpoint on our server `/tfsimulator/$hardwaretype/$growth/$token_price/$cloudunits_price_range`  where the variables corresponds to the data directory structure 

- growth: amount of servers the grid will have in 2025
  - accepted inputs: 50000,100000,200000,600000,1000000,2000000,4000000,10000000,20000000
- token_price: what will the token price be in 5 years from now?
  - accepted inputs: 0.15,0.3,0.6,1,2,3,4,6,10,20,40,100,500,auto
-  cloudunits_price_range:
  - accepted inputs: 1,2,3,4

# Webix wiki page entry point
eventually it will be a page on info_threefold wiki that allows showing components to choose growth, token price, cloud units.

**Comment by despiegk** [comment]
if not done yet then maybe we should do a shortcut
I have about 18 core simulations, we can put them in the config file and work with them like that
its not ideal but can work now, freeing up time for other things.
