### ISSUE TITLE
default template should have smaller margins

### ISSUE THREAD

**Issue by xmonader** [threebotserver/publishingtools#45]
![image](https://user-images.githubusercontent.com/64129/80988987-95bf3080-8e34-11ea-8993-8ec9a4595dad.png)

**Comment by RafyAmgadBenjamin** [comment]
* Increase the margins and remove the Padding 
* I had to override the default values by giving it `important` tag
#### Commit
584b5af5f702c55c032fde832591d6f0ee9fbaac

#### PR
https://github.com/threebotserver/publishingtools/pull/53
