### ISSUE TITLE
Blog: ThreeFold Network logo --> ThreeFold

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#83]
<img width="787" alt="Screen Shot 2020-05-12 at 3 04 56 PM" src="https://user-images.githubusercontent.com/50134479/81694736-fddbcb00-9461-11ea-9f23-0f7d26698ca5.png">

**Comment by abom** [comment]
@samtaggart Can you give me a new image instead of this one (with the same size)

https://github.com/threebotserver/publishingtools/blob/c3e069792497c46a7400e693c855f42577b8e392/src/tfwebserver/static/blog/img/TFT-LOGO.png

**Comment by samtaggart** [comment]
![TFwith3newsize](https://user-images.githubusercontent.com/50134479/81927830-98fcae00-95e4-11ea-8147-d3a991aacca7.png)

**Comment by samtaggart** [comment]
![TFwith3newsize](https://user-images.githubusercontent.com/50134479/81928709-ffce9700-95e5-11ea-8bb8-b8928074c32f.png)

**Comment by abom** [comment]
Using this image now

![TFN-LOGO](https://user-images.githubusercontent.com/511438/81940384-d4ed3e80-95f7-11ea-8fd5-a20a793bd053.png)
