### ISSUE TITLE
Blog: Logo not working above the date in blog articles

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#84]
<img width="788" alt="Screen Shot 2020-05-12 at 3 05 56 PM" src="https://user-images.githubusercontent.com/50134479/81694827-1b109980-9462-11ea-87f2-5bc3c1009ec5.png">

**Comment by abom** [comment]
The original post put the image by hand (as a link), this is not intended, as images are set via metadata, not like this.


```
---
title: "The AirBnB of Internet Capacity"
author: Roel
tags: capacity, decentralization, farming
published_at: 2017-9-12
post_image: airbnb-for-internet-capacity.jpg
---

![Logo](../assets/images/airbnb-for-internet-capacity.jpg)
```

The link `![Logo](../assets/images/airbnb-for-internet-capacity.jpg)` should be removed.
