### ISSUE TITLE
Blog: Can we standardize the image header size?

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#85]
It's bigger in this one – http://134.122.109.244:3000/blog/vonsubblog/posts/hewlett-packard-enterprise--threefold-sign-mou – all the other ones seem to be the same.

**Comment by abom** [comment]
Images are user defined, it's up to all authors to use proper image size for all posts (we cannot force certain sizes, aspect ratio need to be respected...etc)
