### ISSUE TITLE
Blog: Search Issue (Low Priority)

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#86]
<img width="362" alt="Screen Shot 2020-05-12 at 3 27 39 PM" src="https://user-images.githubusercontent.com/50134479/81697348-421c9a80-9465-11ea-9364-6f04c58318b9.png">

It's weird, doesn't pull up the specific instance, just the blog.

**Comment by abom** [comment]
What do you mean exactly by "doesn't pull up the specific instance, just the blog."?

because it shows all the posts it has the word "node"?

**Comment by samtaggart** [comment]
It shows the post, yes, but is there any way to show more detail? Like the sentence where the word is used? If not, can we display the results differently than "posts: the-airbnb-of-internet-capacity" maybe in some more human way? For example, "Post: The Airbnb of Internet Capacity."

**Comment by abom** [comment]
Done, showing post titles now instead of slugs.
