### ISSUE TITLE
Blog: Don't need the pages view

### ISSUE THREAD

**Issue by samtaggart** [threebotserver/publishingtools#87]
http://134.122.109.244:3000/blog

There will only be one blog

**Comment by abom** [comment]
The blogging system is designed to support multiple blogs, if you have a single one, you can just use the full link as http://134.122.109.244:3000/blog/vonsubblog.

**Comment by samtaggart** [comment]
So blog.threefold.io will take the user to http://134.122.109.244:3000/blog/vonsubblog this view? @abom

**Comment by VonSub** [comment]
@samtaggart if we set it up to do so. yes.

**Comment by samtaggart** [comment]
OK well let's make sure we do. :) @VonSub @abom
